version: '3'

services:
  backend:
    build: ./app/backend
    ports:
      - "8000:8000"
    volumes:
      - ./app/backend:/app/backend
    networks:
      - app-network

  frontend:
    build: ./app/frontend
    ports:
      - "8501:8501"
    volumes:
      - ./app/frontend:/app/frontend
    networks:
      - app-network

networks:
  app-network:
